pipeline {
    agent any

    environment {
        DIRECTORY_PATH = '/var/lib/jenkins/workspace/pipeline1_'
        TESTING_ENVIRONMENT = 'test'
        PRODUCTION_ENVIRONMENT = 'id: 222081757'
    }

    stages {
        stage('Build') {
            steps {
                echo 'fetch the source code from the directory path specified by the environment variable'
                echo 'compile the code and generate any necessary artifacts'
            }
        }
        stage('Test') {
            steps {
                echo 'unit tests'
                echo 'integration tests'
            }
        }
        stage('Code Quality Check') {
            steps {
                echo 'check the quality of the code'
            }
        }
        stage('Deploy') {
            steps {
                echo 'deploy the application to a testing environment specified by the environment variable'
            }
        }
        stages('Approval') {
            steps {
                sleep(secs: 10, unit: 'SECONDS')
            }
        }
        stages('Deploy to Production') {
            steps {
                echo 'deploy the code to the production environment: $PRODUCTION_ENVIRONMENT'
            }
        }
    }
}